kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: efk
  labels:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/type: plugins
    xincan.kubernetes.io/role: node
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/app: elasticsearch
spec:
  type: NodePort
  selector:
    xincan.kubernetes.io/company: xincan.cn
    xincan.kubernetes.io/version: 0.0.1
    xincan.kubernetes.io/type: plugins
    xincan.kubernetes.io/role: node
    xincan.kubernetes.io/product: xincan
    xincan.kubernetes.io/app: elasticsearch
  ports:
  - name: node
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 31180
