apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: elasticsearch-node
    namespace: efk
    labels:
      xincan.kubernetes.io/company: xincan.cn
      xincan.kubernetes.io/version: 0.0.1
      xincan.kubernetes.io/type: plugins
      xincan.kubernetes.io/role: node
      xincan.kubernetes.io/product: xincan
      xincan.kubernetes.io/app: elasticsearch
spec:
  replicas: 3
  serviceName: elasticsearch-node-service
  selector:
    matchLabels:
      xincan.kubernetes.io/company: xincan.cn
      xincan.kubernetes.io/version: 0.0.1
      xincan.kubernetes.io/type: plugins
      xincan.kubernetes.io/role: node
      xincan.kubernetes.io/product: xincan
      xincan.kubernetes.io/app: elasticsearch
  template:
    metadata:
      labels:
        xincan.kubernetes.io/company: xincan.cn
        xincan.kubernetes.io/version: 0.0.1
        xincan.kubernetes.io/type: plugins
        xincan.kubernetes.io/role: node
        xincan.kubernetes.io/product: xincan
        xincan.kubernetes.io/app: elasticsearch
    spec:
      serviceAccountName: elasticsearch-admin
      restartPolicy: Always
      containers:
        - name: elasticsearch-node
          image: base.hatech.com.cn/library/elasticsearch:7.4.2-ulimit
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"]
          ports:
            - name: node
              protocol: TCP
              containerPort: 9200
            - name: data
              protocol: TCP
              containerPort: 9300
          env:
            - name: cluster.name
              value: "es_cluster"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: node.master
              value: "false"
            - name: node.data
              value: "true"
            - name: discovery.seed_hosts
              value: "elasticsearch-master-service"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
            - name: node.ingest
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: esdata
  volumeClaimTemplates:
    - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: mysql-nfs-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        # storageClassName: mysql-local-storage
        resources:
          requests:
            storage: 2Gi
